@extends('admin.layout')
@section('title', 'Relatórios')
@section('content')
<div class="admin-head"><div><h1>Relatórios</h1><p>Vendas, produtos e estoque por período.</p></div></div>
<form class="card" method="GET" style="display:flex;gap:12px;align-items:end;flex-wrap:wrap;margin-bottom:20px"><div class="field"><label for="from">De</label><input id="from" name="from" type="date" value="{{ $from }}"></div><div class="field"><label for="to">Até</label><input id="to" name="to" type="date" value="{{ $to }}"></div><button class="btn" type="submit">Atualizar</button></form>
<div class="cards"><div class="metric"><span>Vendas concluídas</span><strong>{{ $saleCount }}</strong></div><div class="metric"><span>Faturamento</span><strong>{{ number_format($revenue, 2, ',', '.') }} Kz</strong></div><div class="metric"><span>Ticket médio</span><strong>{{ number_format($averageTicket, 2, ',', '.') }} Kz</strong></div><div class="metric"><span>Descontos</span><strong>{{ number_format($discounts, 2, ',', '.') }} Kz</strong></div></div>
<div class="admin-head" style="margin-top:30px"><div><h2 style="margin:0">Produtos mais vendidos</h2></div></div><section class="table-wrap"><table><thead><tr><th>Produto</th><th>Quantidade</th><th>Valor dos itens</th></tr></thead><tbody>@forelse ($topProducts as $product)<tr><td>{{ $product->name }}</td><td>{{ $product->quantity_sold }}</td><td>{{ number_format((float) $product->revenue, 2, ',', '.') }} Kz</td></tr>@empty<tr><td colspan="3" class="muted">Não há vendas concluídas no período.</td></tr>@endforelse</tbody></table></section>
<div class="admin-head" style="margin-top:30px"><div><h2 style="margin:0">Posição do estoque</h2></div></div><section class="table-wrap"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Quantidade</th><th>Mínimo</th><th>Situação</th></tr></thead><tbody>@forelse ($stock as $product)@php($quantity = (int) ($product->stock_quantity ?? 0))<tr><td>{{ $product->name }}</td><td>{{ $product->category->name }}</td><td>{{ $quantity }}</td><td>{{ $product->minimum_stock }}</td><td>{{ $quantity === 0 ? 'Sem estoque' : ($quantity <= $product->minimum_stock ? 'Estoque baixo' : 'Normal') }}</td></tr>@empty<tr><td colspan="5" class="muted">Nenhum produto cadastrado.</td></tr>@endforelse</tbody></table></section>
<div class="admin-head" style="margin-top:30px"><div><h2 style="margin:0">Movimentações no período</h2></div></div><section class="table-wrap"><table><thead><tr><th>Data</th><th>Produto</th><th>Tipo</th><th>Quantidade</th><th>Usuário</th><th>Motivo</th></tr></thead><tbody>@forelse ($movements as $movement)<tr><td>{{ $movement->created_at->format('d/m/Y H:i') }}</td><td>{{ $movement->product->name }}</td><td>{{ str($movement->type)->replace('_',' ')->title() }}</td><td>{{ $movement->quantity > 0 ? '+' : '' }}{{ $movement->quantity }}</td><td>{{ $movement->user?->name ?? 'Sistema' }}</td><td>{{ $movement->reason ?? '—' }}</td></tr>@empty<tr><td colspan="6" class="muted">Nenhuma movimentação no período.</td></tr>@endforelse</tbody></table></section>
@endsection
