@extends('admin.layout')
@section('title', $employee->exists ? 'Editar funcionário' : 'Novo funcionário')
@section('content')
<div class="admin-head"><div><h1>{{ $employee->exists ? 'Editar funcionário' : 'Novo funcionário' }}</h1><p>A senha precisa ter pelo menos 12 caracteres.</p></div><a class="btn btn-secondary" href="{{ route('admin.employees.index') }}">Voltar</a></div>
<form class="card admin-form" method="POST" action="{{ $employee->exists ? route('admin.employees.update', $employee) : route('admin.employees.store') }}">@csrf @if ($employee->exists) @method('PUT') @endif
    <div class="field"><label for="name">Nome completo</label><input id="name" name="name" value="{{ old('name', $employee->user?->name) }}" required></div><div class="field"><label for="email">E-mail de acesso</label><input id="email" name="email" type="email" value="{{ old('email', $employee->user?->email) }}" required></div>
    <div class="field"><label for="phone">Telefone</label><input id="phone" name="phone" value="{{ old('phone', $employee->phone) }}"></div><div class="field"><label for="cpf">CPF</label><input id="cpf" name="cpf" value="{{ old('cpf', $employee->cpf) }}"></div>
    <div class="field"><label for="position">Cargo</label><input id="position" name="position" value="{{ old('position', $employee->position) }}"></div>@if (! $employee->exists)<div class="field"><label for="password">Senha inicial</label><input id="password" name="password" type="password" required autocomplete="new-password"></div><div class="field"><label for="password_confirmation">Confirme a senha</label><input id="password_confirmation" name="password_confirmation" type="password" required autocomplete="new-password"></div>@else<div class="field"><label for="password">Nova senha (opcional)</label><input id="password" name="password" type="password" autocomplete="new-password"></div><div class="field"><label for="password_confirmation">Confirme a nova senha</label><input id="password_confirmation" name="password_confirmation" type="password" autocomplete="new-password"></div><div class="field full"><label><input type="checkbox" name="active" value="1" @checked(old('active', $employee->active))> Funcionário ativo</label></div>@endif
    <div class="field full"><strong>Permissões do painel</strong><p class="muted" style="margin:4px 0 12px">Marque apenas os módulos necessários para este funcionário. Administradores sempre têm acesso total.</p><div class="permission-grid">@foreach ($availablePermissions as $permission => $label)<label><input type="checkbox" name="permissions[]" value="{{ $permission }}" @checked(in_array($permission, (array) old('permissions', $employee->permissions ?? []), true))> {{ $label }}</label>@endforeach</div></div>
    <div class="field full"><button class="btn" type="submit">Salvar funcionário</button></div>
</form>
<style>.permission-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.permission-grid label{background:#fcf8f9;border:1px solid var(--line);border-radius:8px;padding:10px;font-weight:400}@media(max-width:650px){.permission-grid{grid-template-columns:1fr}}</style>
@endsection
