@extends('layouts.store')
@section('title', 'Finalizar pedido')
@section('content')
<div class="wrap" style="max-width:850px;padding:32px 0 65px"><div class="section-head"><div><span class="eyebrow" style="color:var(--wine)">Quase lá</span><h1 style="font-size:38px;margin:5px 0">Finalizar pedido</h1><p>Revise a entrega e escolha a forma de pagamento.</p></div></div>
    @if ($errors->any())<div class="notice" style="margin-bottom:18px;background:#fff0ed;color:#a23d2c;border-color:#f0cfc8">@foreach ($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
    <form method="POST" action="{{ route('checkout.store') }}" style="display:grid;gap:20px">@csrf
        <section style="background:white;border:1px solid var(--line);border-radius:14px;padding:22px"><h2 style="font-size:19px">1. Endereço de entrega</h2>
            @forelse ($addresses as $address)<label style="display:flex;gap:10px;padding:12px;border:1px solid var(--line);border-radius:9px;margin:8px 0"><input type="radio" name="address_id" value="{{ $address->id }}" @checked(old('address_id', $addresses->firstWhere('is_default', true)?->id ?? $addresses->first()?->id) == $address->id)><span>{{ $address->street }}, {{ $address->number }} · {{ $address->neighborhood }}, {{ $address->city }} - {{ $address->state }} · CEP {{ $address->zipcode }}</span></label>@empty<p style="color:var(--muted)">Cadastre um endereço para receber seu pedido.</p>@endforelse
            <label style="display:flex;gap:10px;padding:12px;border:1px solid var(--line);border-radius:9px;margin:8px 0"><input type="radio" name="address_id" value="" @checked(old('address_id') === '')><span>Usar um novo endereço</span></label>
            <details style="margin-top:15px" @if ($addresses->isEmpty() || old('address_id') === '') open @endif><summary style="color:var(--wine);font-weight:700;cursor:pointer">Adicionar endereço</summary><div style="display:grid;grid-template-columns:1fr 2fr;gap:10px;margin-top:14px">@foreach (['zipcode' => 'CEP', 'street' => 'Rua', 'number' => 'Número', 'complement' => 'Complemento', 'neighborhood' => 'Bairro', 'city' => 'Cidade', 'state' => 'UF'] as $key => $label)<label style="font-size:12px">{{ $label }}<input name="{{ $key }}" value="{{ old($key) }}" maxlength="255" style="display:block;width:100%;margin-top:4px;padding:10px;border:1px solid var(--line);border-radius:8px"></label>@endforeach</div></details>
        </section>
        <section style="background:white;border:1px solid var(--line);border-radius:14px;padding:22px"><h2 style="font-size:19px">2. Pagamento</h2><p style="color:var(--muted);font-size:13px">O pedido fica aguardando confirmação. Pagamentos online serão integrados posteriormente.</p><div style="display:flex;flex-wrap:wrap;gap:12px">@foreach (['PIX' => 'PIX', 'CASH' => 'Dinheiro', 'DEBIT_CARD' => 'Cartão de débito', 'CREDIT_CARD' => 'Cartão de crédito'] as $value => $label)<label style="padding:11px;border:1px solid var(--line);border-radius:9px"><input type="radio" name="payment_method" value="{{ $value }}" @checked(old('payment_method', 'PIX') === $value)> {{ $label }}</label>@endforeach</div></section>
        <section style="background:white;border:1px solid var(--line);border-radius:14px;padding:22px"><h2 style="font-size:19px">3. Itens</h2>@foreach ($cart->items as $item)<div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--line)"><span>{{ $item->quantity }} × {{ $item->product->name }}</span><span>R$ {{ number_format($item->quantity * (float) $item->product->sale_price, 2, ',', '.') }}</span></div>@endforeach<div style="display:flex;justify-content:space-between;font-weight:800;font-size:19px;margin-top:15px"><span>Total</span><span>R$ {{ number_format((float) $subtotal, 2, ',', '.') }}</span></div></section>
        <button class="button" style="justify-self:end;padding:13px 22px" type="submit">Confirmar pedido</button>
    </form>
</div>
@endsection
