@extends('admin.layout')
@section('title', 'Pedidos')
@section('content')
<div class="admin-head"><div><h1>Pedidos</h1><p>Acompanhe e atualize os pedidos da loja.</p></div></div>
<form method="GET" class="card" style="display:flex;gap:10px;margin-bottom:18px;flex-wrap:wrap"><input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Número do pedido" style="padding:10px;border:1px solid var(--line);border-radius:8px"><select name="status" style="padding:10px;border:1px solid var(--line);border-radius:8px"><option value="">Todos os status</option>@foreach (['PENDING','CONFIRMED','SEPARATING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select><button class="btn" type="submit">Filtrar</button></form>
<section class="table-wrap"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Data</th><th>Total</th><th>Pagamento</th><th>Status @if (auth()->user()->hasPermission('orders.manage'))/ atualização@endif</th></tr></thead><tbody>
@forelse ($orders as $order)<tr><td><strong>{{ $order->order_number }}</strong></td><td>{{ $order->customer->user->name }}</td><td>{{ $order->created_at->format('d/m/Y H:i') }}</td><td>R$ {{ number_format((float) $order->total, 2, ',', '.') }}</td><td>@foreach ($order->payments as $payment)<div>{{ str($payment->method)->replace('_',' ')->title() }} · {{ str($payment->status)->title() }}</div>@endforeach</td><td>@if (auth()->user()->hasPermission('orders.manage'))<form action="{{ route('admin.orders.update', $order) }}" method="POST" style="display:flex;gap:6px;min-width:240px">@csrf @method('PATCH')<select name="status" style="padding:8px;border:1px solid var(--line);border-radius:8px" @disabled(in_array($order->status,['DELIVERED','CANCELLED'],true))>@foreach (['PENDING','CONFIRMED','SEPARATING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'] as $status)<option value="{{ $status }}" @selected($order->status === $status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select><button class="btn btn-secondary" type="submit" @disabled(in_array($order->status,['DELIVERED','CANCELLED'],true))>Salvar</button></form>@else{{ str($order->status)->replace('_', ' ')->title() }}@endif</td></tr>@empty<tr><td colspan="6" class="muted">Nenhum pedido encontrado.</td></tr>@endforelse
</tbody></table></section><div style="margin-top:20px">{{ $orders->links() }}</div>
@endsection
